### ISSUE TITLE
Error bei Contao 3.5.0

### ISSUE THREAD

**Issue by mstudio-dev** [terminal42/contao-mailusername#7]
Ich bekomme bei C 3.5.0 einen Error: "Column 'username' cannot be null".
Liegt vielleicht daran, dass sich bei 3.5 das Feld geändert hat: 'sql' => "varchar(64) COLLATE utf8_bin NULL" (3.4.5: 'sql' => "varchar(64) COLLATE utf8_bin NOT NULL default ''")

**Comment by aschempp** [comment]
@qzminski could be a time-filler for you? :-)

**Comment by qzminski** [comment]
Fixed in 26e4fca.

The problem lied in the below line of registration module. The username is obviously empty in this case and the only way we can alter it is through the model that is already in the model registry.

https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleRegistration.php#L450

**Comment by aschempp** [comment]
Looks good, but:

 1. Cody style seems to be wrong (if I look at the GitHub diff)
 2. Shouldn't we check for `null` on the `findByPk()` method?

**Comment by qzminski** [comment]
1. Yes because the old code is still tabs.
2. In theory maybe yes, but in practice it would never be the case.

**Comment by aschempp** [comment]
Can you fix both then please? Coding style for old code and the null-check?

**Comment by qzminski** [comment]
Both fixed in 677308f and a34d17e. It now uses the ```Model::refresh()``` method instead of overidding the username value.

**Comment by mstudio-dev** [comment]
Funzt. Thank You!
